spring:
  application:
    name: agent



langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENROUTER_API_KEY}
      model-name: openrouter/free
      base-url: https://openrouter.ai/api/v1





