spring:
  application:
    name: agent

agent:
  capability:
    ttl: 3
  plan:
    max-steps: 10
    timeout-per-step: 30000



langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENROUTER_API_KEY}
      model-name: openrouter/free
      base-url: https://openrouter.ai/api/v1





